In [1]:
import pandas as pd
import numpy as np

In [15]:
reddit_body = pd.read_csv("soc-redditHyperlinks-body.tsv", sep='\t',header='infer')
reddit_title = pd.read_csv("soc-redditHyperlinks-title.tsv", sep='\t',header='infer')
reddit_title.head()

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,PROPERTIES
0,rddtgaming,rddtrust,1u4pzzs,2013-12-31 16:39:18,1,"25.0,23.0,0.76,0.0,0.44,0.12,0.12,4.0,4.0,0.0,..."
1,xboxone,battlefield_4,1u4tmfs,2013-12-31 17:59:11,1,"100.0,88.0,0.78,0.02,0.08,0.13,0.07,16.0,16.0,..."
2,ps4,battlefield_4,1u4tmos,2013-12-31 17:59:40,1,"100.0,88.0,0.78,0.02,0.08,0.13,0.07,16.0,16.0,..."
3,fitnesscirclejerk,leangains,1u50xfs,2013-12-31 19:01:56,1,"49.0,43.0,0.775510204082,0.0,0.265306122449,0...."
4,fitnesscirclejerk,lifeprotips,1u51nps,2013-12-31 21:02:28,1,"14.0,14.0,0.785714285714,0.0,0.428571428571,0...."

In [16]:
reddit_body_merge = reddit_body.drop(['PROPERTIES', 'POST_ID'], axis = 1)
reddit_title_merge = reddit_title.drop(['PROPERTIES', 'POST_ID'], axis = 1)
reddit_body_merge.head()

  SOURCE_SUBREDDIT TARGET_SUBREDDIT            TIMESTAMP  LINK_SENTIMENT
0  leagueoflegends  teamredditteams  2013-12-31 16:39:58               1
1       theredlion           soccer  2013-12-31 18:18:37              -1
2     inlandempire           bikela  2014-01-01 14:54:35               1
3              nfl              cfb  2013-12-31 17:37:55               1
4       playmygame          gamedev  2014-01-01 02:51:13               1

In [17]:
reddit_posts = reddit_body_merge.append(reddit_title_merge)

In [19]:
reddit_posts['month'] = pd.DatetimeIndex(reddit_posts['TIMESTAMP']).month
reddit_posts['year'] = pd.DatetimeIndex(reddit_posts['TIMESTAMP']).year
reddit_posts.head()

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,TIMESTAMP,LINK_SENTIMENT,month,year
0,leagueoflegends,teamredditteams,2013-12-31 16:39:58,1,12,2013
1,theredlion,soccer,2013-12-31 18:18:37,-1,12,2013
2,inlandempire,bikela,2014-01-01 14:54:35,1,1,2014
3,nfl,cfb,2013-12-31 17:37:55,1,12,2013
4,playmygame,gamedev,2014-01-01 02:51:13,1,1,2014

In [20]:
reddit_posts.to_csv('Start_Reddit.csv')